name: Branch-specifics Tests
on:
  pull_request:
    branches: [main,staging]
  push:
    branches: [main,staging]

jobs:
  pr_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Installation des d√©pendances
        run: composer install
