name: Branch-specifics Tests
on:
  pull_request:
    branches: [main,master,test-de-code]
  push:
    branches: [main,master,test-de-code]

jobs:
  pr_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Installation des dépendances
        run: composer install
      - name: Création base
        run: php bin/console doctrine:database:create --env=test
      - name: Création Schema
        run: php bin/console doctrine:schema:create --env=test
      - name: test d'unitaire Event
        run: php bin/phpunit tests/form/EventsControllerTest.php
      - name: test d'unitaire Artist
        run: php bin/phpunit tests/form/ArtistControllerTest.php
      - name: test d'intégration
        run: php bin/phpunit tests/integration/UserRepositoryTest.php





