name: Branch-specifics Tests
on:
  pull_request:
    branches: [main,test-de-code]
  push:
    branches: [main,test-de-code]

jobs:
  pr_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
      - name: Installation des d√©pendances
        run: composer install